version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mosbot-backend
    restart: always
    environment:
      - PORT=${PORT_BACKEND}
      - MONGO_URL=${MONGO_URL}
      - BACKEND_LINK=${BACKEND_LINK}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - BOT_TOKEN=${BOT_TOKEN}
    ports:
      - ${PORT_BACKEND}:${PORT_BACKEND}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}      
    container_name: mosbot-frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend          